name: CD to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check SSH connection
        run: ssh -o StrictHostKeyChecking=no quinten@164.92.80.193 'echo "SSH connection successful!"'

      - name: SSH into droplet and run script
        run: |
          echo ${{ secrets.USER_PASSWORD }} | ssh -o StrictHostKeyChecking=no quinten@164.92.80.193 'sudo -S ./cd-script'
