name: Jenkins Pipeline

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins pipeline
        run: |
          curl -X POST -u ${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_TOKEN }} \
            -F "token=${{ secrets.JENKINS_PIPELINE_TOKEN }}" \
            -F "ref=${{ github.head_ref }}" \
            -F "repository=${{ github.repository }}" \
            -F "owner=${{ github.repository_owner }}" \
            https://your-jenkins-url.com/generic-webhook-trigger/invoke?token=${{ secrets.JENKINS_TRIGGER_TOKEN }}
